version: '3'
services:
    db:
        image: mongo:3.6
        container_name: mongodb
        ports:
            - 27017:27017
    server:
        image: node:12
        env_file: 
            - ./.env
        ports:
            - ${PORT}:${PORT}
        command: bash -c "npm i && node server"
        volumes: 
            - ./:/server
        depends_on: 
            - db