version: '3'
services:
    db:
        image: mongo:3.4
        ports:
            - 27017:27017
    server:
        image: node:15.0.1-alpine3.11
        env_file: 
            - .env
        ports:
            - ${PORT}:${PORT}
        command: ash -c "cd server/ && npm i && node server"
        volumes: 
            - .:/server
        depends_on: 
            - db